apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devshares.devworkspace.webide.com
spec:
  group: devworkspace.webide.com
  names:
    kind: devworkspaceshare
    listKind: devworkspaceshareList
    plural: devshares
    singular: devworkspaceshare
  scope: Cluster
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---        
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devworkspace-share-role
rules:
- apiGroups: ["devworkspace.webide.com"]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devworkspace-share-rolebinding
subjects:
- kind: Group
  name: system:authenticated # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: devworkspace-share-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-reader-rolebind
subjects:
- kind: Group
  name: system:authenticated # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: dex
  apiGroup: rbac.authorization.k8s.io